server:
  port: 8081
spring:
  application:
    name: news
news:
  api: 67812bd06ac34a7f90694607da85dcb5
  url: https://newsapi.org/v2/everything
  domains: autosport.com
  language: en
  sortBy: publishedAt
  pageSize: 10
  query:
    exclude: speed, technology, business, health, science
    keywords: Formula 1,racing,Grand Prix
  